# Generated by Django 5.1.4 on 2025-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=30),
            preserve_default=False,
        ),
    ]
